### ISSUE TITLE
unwrap fail in attach_el_and_children

### ISSUE THREAD

**Issue by neyo8826** [David-OConnor/seed#194] opened 2019-08-10 08:16 UTC
```rust
fn view(model: &Model) -> impl View<Msg> {
	use seed::*;

	let mut content = vec![p![button!["Load sample sheet", simple_ev(Ev::Click, Msg::LoadSample)]]];
	if let Some(sheet) = &model.sheet {
		content.push(h2![sheet.name]);
	}
	content
}
```

`model.sheet` is an `Option` width starting value of `None`. `Msg::LoadSample` causes `model.sheet` to be filled. The nex render will panic:

```
panicked at 'Missing websys el in attach_el_and_children', src/libcore/option.rs:1036:5

Stack:

init/imports.wbg.__wbg_new_59cb74e423758ede@http://localhost:8080/wui:341:25
console_error_panic_hook::Error::new::h2c82db63be72f6c9@http://localhost:8080/wui_bg:wasm-function[3711]:0xf9287
console_error_panic_hook::hook_impl::hb474f5d955503f9c@http://localhost:8080/wui_bg:wasm-function[635]:0x85e0b
console_error_panic_hook::hook::hc74801f66fc9d706@http://localhost:8080/wui_bg:wasm-function[4076]:0xfeafe
core::ops::function::Fn::call::hbc0f932c6a30728a@http://localhost:8080/wui_bg:wasm-function[3728]:0xf973e
std::panicking::rust_panic_with_hook::h3f88564dfeb012eb@http://localhost:8080/wui_bg:wasm-function[1002]:0xa369e
std::panicking::continue_panic_fmt::he2d0fc2a935878af@http://localhost:8080/wui_bg:wasm-function[2402]:0xdd62e
rust_begin_unwind@http://localhost:8080/wui_bg:wasm-function[4968]:0x107c48
core::panicking::panic_fmt::hc4f83bfed80aeabd@http://localhost:8080/wui_bg:wasm-function[3872]:0xfbb2e
core::option::expect_failed::he602aa67d6d2d670@http://localhost:8080/wui_bg:wasm-function[2978]:0xeb558
core::option::Option<T>::expect::h441f04ca1dad8fdd@http://localhost:8080/wui_bg:wasm-function[1092]:0xa9193
seed::websys_bridge::attach_el_and_children::h4256bb1c7b87f87b@http://localhost:8080/wui_bg:wasm-function[252]:0x544ed
seed::vdom::App<Ms,Mdl,ElC,GMs>::rerender_vdom::h7120787c826fec40@http://localhost:8080/wui_bg:wasm-function[104]:0x136e4
seed::vdom::App<Ms,Mdl,ElC,GMs>::schedule_render::{{closure}}::hfeb66b8248530459@http://localhost:8080/wui_bg:wasm-function[987]:0xa25ac
<dyn +core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h87120ca74b0c1b70@http://localhost:8080/wui_bg:wasm-function[1015]:0xa448e
__wbg_elem_binding2@http://localhost:8080/wui:61:41
real@http://localhost:8080/wui:1163:24
```

There is no leftover DOM node, AFAIK, to reuse.

I have an annoying workaround which seem sto hide the problem:
```rust
if let Some(sheet) = &model.sheet {
	content.push(h2![sheet.name]);
} else {
	content.push(empty!());
}
```
Don't know, what happens for large lists.

**Comment by David-OConnor** [comment] 2019-08-12 05:28
I'm able to reproduce. Standby.

**Comment by David-OConnor** [comment] 2019-08-12 05:41
> This bug only occurs when there are multiple top-level elements, so another workaround is to have your view fn return an element like `div` or `section` instead of `Vec`.

**Comment by David-OConnor** [comment] 2019-08-12 05:52
Fixed in latest commit. Recommend you continue using that workaround (or the one I posted) until the next release. This was due to something a line I erroneously commented-out in the 0.4.0 release.

**Closed** 2019-09-23 07:16 UTC
Labels: bug
