### ISSUE TITLE
Rendering issue with similar elements under different parents.

### ISSUE THREAD

**Issue by thedodd** [David-OConnor/seed#89] opened 2019-03-29 17:12 UTC
I've been running into an issue where I have a few views which have a somewhat similar layout.

When the view is changed, the child elements which are similar are not updated. It would seem that the diffing algorithm is not taking into account certain attributes during the diff. The exact issue is as follows:
- two different parent elements with similar layout.
- both have an input element. The placeholders are different and even their bound `At::Value`s are different.
- when switching between the views, the input elements are not updated.

I tried using different IDs on the parent elements which are being changed, in hopes that the diffing algorithm would see this as a fundamentally different element and invalidate all of its children, but I know there are lots of nuances here.

I have the code in a public repo, let me know if you need repro steps.

**Comment by David-OConnor** [comment] 2019-04-02 00:37
Probably something simple I overlooked in the patch function in vdom.rs . A repo or steps would be appreciated

**Comment by thedodd** [comment] 2019-04-02 03:18
The repo is here: https://github.com/thedodd/giphy-api. The code is under client/src/containers/ and the two offending modules are search.rs and favorites.rs. 

Thanks David. If I get some time over the next few days I’ll take a look at vdom.rs as well and see if anything sticks out to me.

**Comment by David-OConnor** [comment] 2019-04-03 19:42
I'm able to reproduce. Might be related to controlled components, vice patching: This example changes the text color when page changes, but not the content:

```rust
#[macro_use]
extern crate seed;
use seed::prelude::*;

struct Model {
    pub page: u8,
    pub val1: String,
    pub val2: String,
}

impl Default for Model {
    fn default() -> Self {
        Self {
            page: 0,
            val1: "A".into(),
            val2: "B".into(),
        }
    }
}

#[derive(Clone)]
enum Msg {
    ChangePage(u8),
    ChangeVal1(String),
    ChangeVal2(String),
}

fn update(msg: Msg, model: &mut Model) -> Update<Msg> {
    match msg {
        Msg::ChangePage(page) => model.page = page,
        Msg::ChangeVal1(val) => model.val1 = val,
        Msg::ChangeVal2(val) => model.val2 = val,
    }
    Render.into()
}

fn view(model: &Model) -> Vec<El<Msg>> {
    let mut next_page = 0;
    if model.page == 0 { 
        next_page = 1;
    }

    vec![
        button![
            simple_ev(Ev::Click, Msg::ChangePage(next_page)),
            format!("Change to page {}", next_page)
        ],
        if model.page == 0 {
            input![ style!{"color" => "blue"}, input_ev(Ev::Change, Msg::ChangeVal1) ]
        } else {
            input![ input_ev(Ev::Change, Msg::ChangeVal2) ]
        }
    ]
}

#[wasm_bindgen]
pub fn render() {
    seed::App::build(Model::default(), update, view)
        .finish()
        .run();

}
```

**Comment by David-OConnor** [comment] 2019-04-04 03:10
I think all of my above suggestions as to the cause are incorrect. Suspect something subtle in the way input text is stored in the DOM; ie not a text node, and not the `value` attribute. When I inspect them in my example above, there's no text node, and the value attribute patches correctly... while showing the wrong text.

**Comment by thedodd** [comment] 2019-04-04 15:23
@David-OConnor copy that. I'll try the latest commit and report back.

**Comment by thedodd** [comment] 2019-04-04 16:28
@David-OConnor so, I can definitely confirm that your analysis seems to be correct. When the page is switched, the value attribute on the new node is set to `value=""`, but in the UI it still retains the value of the input from the previous page.

I set the client app's seed dep to: `seed = { git="https://github.com/David-OConnor/seed.git", rev="278b77a951be6dbeac90d7f829e03fea93f45440" }`. Here is the branch if you are interested in trying it out: https://github.com/thedodd/giphy-api/tree/seed-diagnostics

**Comment by David-OConnor** [comment] 2019-04-04 23:08
When I try to build that, I get errors about OpenSSL. Did the latest commit have any effect on the input behavior?

**Comment by thedodd** [comment] 2019-04-05 01:36
@David-OConnor hmm, that's interesting. The docker container has all the system level dependencies needed. I did a build with --no-cache when I updated too. Strange.

As far as the input behavior, it appears to be the same. When the page is switched, the value attribute on the new input element is set to `value=""`, but in the UI it still retains the value of the input element from the previous page.

**Comment by David-OConnor** [comment] 2019-04-05 01:55
Is there a way to repro this without Docker? Like, modifying the example code I posted above? Struggling to get Docker to work / it wants me to change BIOS settings which sounds like a red flag.

**Comment by thedodd** [comment] 2019-04-05 14:49
@David-OConnor hmm. I decided to use docker in this case so that it would run the same way across anyone's machine. If you can't run docker, then you'll just need to invoke the standard cargo builds.

I'll push an update to the README real quick on how to do that. Sec.

**Comment by thedodd** [comment] 2019-04-05 16:13
@David-OConnor ok, I've pushed some updates here: https://github.com/thedodd/giphy-api/pull/2

If you are on that branch, you should have some solid detailed instructions on [how to run this outside of docker](https://github.com/thedodd/giphy-api/blob/5057215e787fd7213d72eab7b1c696a1ac331b0c/README.md#non-docker-development). I included a section on non-posix environments ... I don't really use Windows at all, so I'm not sure that I will be able to help with diagnostics there much. Keep me posted.

If you were running into OpenSSL issues on your machine, it may actually be easiest to just install [docker for windows](https://docs.docker.com/docker-for-windows/install/). It is very well trusted by the community (who doesn't use docker these days), and it will probably be easier than jumping through a lot of hoops to deal with OpenSSL issues on Windows.

**Comment by David-OConnor** [comment] 2019-04-06 14:06
Got docker working, but not sure how to run the example with it. I tried going a directly up, and running `docker build giphy-api`; it outputs text about being successfully built, but not sure how to go from there to running the server. Would like to get to the bottom on this, beyond what adding `set_location` fixes.

**Comment by David-OConnor** [comment] 2019-04-07 17:04
I've got Docker working, pulled the repo, checked-out the `seed-diagnostics` branch, ran `docker-compose up -d` and `docker-compose logs -f`, and opened `localhost:8080`, and receive the following error in Firefox:

```
The script from “http://localhost:8080/pkg/package.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.[Learn More]
SyntaxError: expected expression, got '<'
ReferenceError: wasm_bindgen is not defined
```

**Comment by thedodd** [comment] 2019-04-07 22:16
@David-OConnor that's definitely quite strange because there is nothing in the repo that calls for a `/pkg/package.js` file to be loaded at all ... is there another application you have running on the system which is attempting to serve on port 8080? Maybe something outside of the docker context?

**Comment by David-OConnor** [comment] 2019-04-07 22:21
You're correct - appears a docker server was running from prev troubleshooting under Docker Desktop.

**Comment by thedodd** [comment] 2019-04-08 01:18
Perhaps there is some sort of application which is starting the other docker container. There are a few ways to deal with it. Killing the old container and then restarting the one we are interested in should do the trick:
- `docker ps` to find the ID of the other container which is using port 8080. The ID should be the first column.
- `docker rm -f ${offending_container_id}`, where `${offending_container_id}` is obvs the ID we just copied.
- From the root of the repo we are working from: `docker-compose down` to bring everything down, and then `docker-compose up -d` to bring everything back up (should NOT require a rebuild).

Let me know if that helps ... I'm really sorry that the setup has caused this much trouble ... usually the docker based approach is effortless. Everyone's machine has differences though.

PS
If all of that does not successfully remove the offending container, or it is just immediately re-spawned, then there is some other app which is monitoring the container and causing it to re-spawn. Next best thing to do would be to simply change the port that our container is using. Super simple to do so ... just let me know.

**Comment by David-OConnor** [comment] 2019-04-08 23:55
Go with instructions for changing port. (Tried replacing all instances of "8080" with "8081" in the proj folder, but appears to break something docker-related.

The set_value fix made it into the latest release.

**Comment by thedodd** [comment] 2019-04-12 15:56
@David-OConnor ok, I've updated the code & merged it into the master branch. It is now using seed `0.3.1`, the port have been changed over to `9000`, and it looks like the rendering issue has been fixed!!! Woot woot!

Thanks for all the awesome work on this, @David-OConnor! It has been quite enjoyable using this framework! I'll close this issue now.

**Comment by thedodd** [comment] 2019-04-12 16:58
I lied ... unfortunately it looks like it is still there. The project is available for testing though.

**Comment by David-OConnor** [comment] 2019-04-18 16:32
Trying to repro this on Windows Subsys for Linux. When I run 'cargo run' in the main directory, I receive this message:
```rust
thread 'main' panicked at 'MissingValue(
    "port"
)', server/src/config.rs:32:25
```
I'd like to fix this, but need to repro it first. Can you provide a [MCV](https://stackoverflow.com/help/mcve) example?

**Comment by thedodd** [comment] 2019-04-18 22:19
Man, I’m really sorry about how much trouble you’ve had with getting this thing running. Normally a single `docker-compose up -d` command is the only thing anyone will need to do. 

However, if you can’t run docker ... well, I just don’t want to add all the overhead of accounting for platform inconsistencies. It’s gotta be all docker. 

I did change the ports with the most recent updates to master, so I would encourage you to try that again. You shouldn’t run into that random issue with a ghost container on your system anymore. 

However, I will go ahead and create a super simple example unrelated to the reference app I’ve been working on.

**Comment by thedodd** [comment] 2019-04-18 22:22
Oh yea: https://github.com/thedodd/giphy-api/blob/master/README.md#non-docker-development

That section has everything you need if you can’t run docker. I’ll still make the MCV though.

**Comment by MartinKavik** [comment] 2019-05-14 18:09
I've just tested it (current master on https://github.com/thedodd/giphy-api + compose up) and I didn't see any problems with inputs. I tried to switch pages, add favorite gifs, search, logout/login, etc., but everything seems ok. (Firefox, Chrome + Windows 10).

I have to update `/client/Cargo.toml` because of a new wasm-bindgen version (compilation was failing):
```
[dependencies]
common = { path="../common" }
futures = "0.1"
js-sys = "=0.3.20"
lazy_static = "1.3"
log = "0.4"
seed = "0.3.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
wasm-bindgen = "0.2.43"
web-sys = { version="0.3.20", features=["Storage", "Window"]}
validator = "0.8"
```
But I doubt it fixed something.

@thedodd: Is it still problem for you? And can you add that MCV? (ideally updated for current Seed and included in `/examples` + tried with `cargo make start 89_bug_example`). Otherwise I suggest to close this issue.

@David-OConnor `it wants me to change BIOS settings` - Why is it red flag? I've just enabled virtualization in BIOS as usual. I also had to uninstall Hyper-V and install again so new Docker finally started working. Then I start `docker-compose up` from cmd/ps/git-bash (without linux subsys) and after 10min I was able to connect to `localhost:9000`.

**Comment by David-OConnor** [comment] 2019-05-14 21:40
I was unfamiliar with the Docker workflow; got past that error by enabling virtualization as you described. I think I gave up on Docker too early / didn't feel like learning it at the time.

**Comment by MartinKavik** [comment] 2019-05-15 05:47
-OT-
@David-OConnor I only know, how to start it and do some basic configuration, I can't escape it as mostly a backend developer.
2 tips:
1. Install [Kitematic](https://kitematic.com/): 
   - (Right click on Docker icon in taskbar -> Kitematic -> click on link -> download to recommended folder and rename it to `Kitematic` -> click again on Kitematic in Docker context menu)
   - It allows you to easy stop running containers, set their ports, download new containers (e.g. Postgre), etc.

2. You can create a new Windows user and use it to limit Docker access to your disks. [Guide](https://forums.docker.com/t/how-to-share-windows-drives-with-a-user-without-password/22933/6).

**Comment by thedodd** [comment] 2019-05-16 15:10
@MartinKavik hey, thanks for checking up on that. Like a fool, I removed the branch that showed the issue. In master, I've implemented a workaround. I think I removed it because I didn't think anyone else would be interested in taking a look. The workaround was to use fundamentally different element types on the different pages to avoid the diffing issues. So the branch will just modify the code to use the normal elements and attributes that I would want to use.

I'll circle back once I've made those changes.

**Comment by thedodd** [comment] 2019-05-16 17:02
Ok, @MartinKavik I've pushed the reverted workaround to the `seed-diagnostics` branch. You should be able to test it out and see the issue once again. You can see in the gif I've attached here that the icon is not updating. The favorites page should have a filter icon (which works in master because of my workaround).

![icon-not-updating](https://user-images.githubusercontent.com/2380740/57872913-73bb4100-77d2-11e9-8adb-2d61d6e7202c.gif)

**Comment by MartinKavik** [comment] 2019-05-30 16:15
> You can see in the gif I've attached here that the icon is not updating.

The problem is `font-awesome` - it modifies DOM:

From:
```html
<i class="fas fa-filter"></i> 
```
To:
```html
<svg class="svg-inline--fa fa-filter fa-w-16" aria-hidden="true" data-prefix="fas" data-icon="filter" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg=""><path fill="currentColor" d="M487.976 0H24.028C2.71 0-8.047 25.866 7.058 40.971L192 225.941V432c0 7.831 3.821 15.17 10.237 19.662l80 55.98C298.02 518.69 320 507.493 320 487.98V225.941l184.947-184.97C520.021 25.896 509.338 0 487.976 0z"></path></svg>
<!-- <i class="fas fa-filter"></i> -->
```

So I think it's the reason, why FA components exist for specific frameworks.

---

Minimal example: 
- https://github.com/MartinKavik/seed/blob/fix/89-similar-elements/examples/89_similar_elements_bug_demo/src/lib.rs
- https://github.com/MartinKavik/seed/blob/fix/89-similar-elements/examples/89_similar_elements_bug_demo/index.html

Patch algorithm seems to works fine if you delete  `<script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>` from `index.html`.

@David-OConnor Do you this there is a way how to resolve it without writing a font-awesome library(?) for Seed?

---

OT:
@thedodd I have problems with running giphy-api in "development mode":
Is `docker-compose run -v ./static:/api/static -p 9000:9000 server cargo m
ake watch-client` the right way to start it?

Because both commands:
- `docker-compose run -v ./static:/api/static -p 9000:9000 server cargo make watch-server-run`
-  `docker-compose run -v ./static:/api/static -p 9000:9000 server cargo make watch-client`

fail with:
```
$ docker-compose run -v ./static:/api/static -p 9000:9000 server cargo make watch-ser
ver-run
ERROR: Cannot create container for service server: b'Mount denied:\nThe source path "s
tatic;C:\\\\Program Files\\\\Git\\\\api\\\\static"\nis not a valid Windows path'
```
Windows 10, git-bash

**Comment by David-OConnor** [comment] 2019-05-30 16:32
Great find. No solution comes to mind - my understanding is frontend frameworks assume minimal DOM manipulation by the app. Alternatives here are unicode:  `☰  × 🔍` , or SVG if you want to ensure uniform display across devices

**Comment by thedodd** [comment] 2019-06-21 19:38
@MartinKavik hey, sorry for the ultra late response. So, those two docker-compose commands are definitely correct. I'm not sure why they would be failing on windows. I don't have a windows machine to do troubleshooting, but it sounds like a windows specific issue with docker/docker-compose.

@David-OConnor thanks for bearing with me on this issue. I definitely agree that font-awesome is manipulating the DOM which could certainly lead to rendering issues. 

Feel free to close this issue.

**Closed** 2019-06-25 07:01 UTC
